name             'just_chew'
maintainer       'Gannon McGibbon'
maintainer_email 'self@gannon.io'
license          'MIT'
description      'Installs/Configures just_chew'
long_description 'Installs/Configures just_chew'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'vim',         '~> 2.0.2'
depends 'nodejs',      '~> 3.0.0'
depends 'phantomjs2',  '~> 1.1.0'
depends 'imagemagick', '~> 0.2.3'
depends 'ruby_build',  '~> 1.1.0'
depends 'ruby_rbenv',  '~> 1.2.0'
depends 'postgresql',  '~> 6.1.1'
